[noup] zephyr: Fix header file path
Fix header include path for eloop.h when
including ctrl_iface_zephyr.h from another module.

Issue is observed while compiling the Wi-Fi shell sample
with enterprise mode support enabled. Include eloop.h
in `ctrl_iface_zephyr.h` using a relative path, which causes
a build failure when the file is included from outside the
supplicant module.

Build error:
  fatal error: eloop.h: No such file or directory

Signed-off-by: Triveni Danda <triveni.danda@nordicsemi.no>